version: '3.3'

services:
  core:
    image: tokend/core:3.6.3.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=core
      - POSTGRES_DB=core
      - PGDATA=/data/pgdata
      - ENSUREDB=1
      - CONFIG=/core-config.ini
    volumes:
      - ./configs/core.ini:/core-config.ini
      - core-data:/data
    ports:
      - "8080:8080"
  horizon:
    image: tokend/horizon:3.8.0
    ports:
      - "8000:80"
    depends_on:
      - core
    restart: unless-stopped
    environment:
      - POSTGRES_USER=horizon
      - POSTGRES_PASSWORD=horizon
      - POSTGRES_DB=horizon
      - PGDATA=/pgdata
    volumes:
      - ./configs/horizon.yaml:/config.yaml
volumes:
  core-data:
  horizon-data:
