config:
  stellar_core_url:                        http://core:8080
  stellar_core_database_url:               postgres://core:core@core/core?sslmode=disable
  hostname:                                ""
  database_url:                            postgres://horizon:horizon@localhost/horizon?sslmode=disable
  log_level:                               "warn"
  slow_query_bound:                        1s
  port:                                    80
  ingest:                                  true
  stale_threshold:                         0
  sign_checkskip:                          false
  cors_enabled:                            false
  disable_api_submit:                      true
  disable_tx_tfa:                          true
  force_https_links:                       false
  project:                                 "horizon"
  env:                                     "auditor"
  migrate_up_on_start:                     true
  api_backend:                             http://black.hole
  template_backend:                        http://black.hole
  invest_ready:                            http://black.hole
  telegram_airdrop:                        http://black.hole

janus:
  disabled: true
